multiserver/app/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.ServerListView.as_view(), name="list"),
    path("create/", views.ServerCreateView.as_view(), name="create"),
    path("<int:server_id>/", views.ServerDetailView.as_view(), name="detail"),
    path("<int:server_id>/update/", views.ServerUpdateView.as_view(), name="update"),
    path("<int:server_id>/delete/", views.ServerDeleteView.as_view(), name="delete"),
    path("<int:server_id>/initialize/", views.initialize_view, name="initialize"),
    path("<int:server_id>/apply-nginx/", views.apply_nginx_view, name="apply_nginx"),
    path("<int:server_id>/apply-systemd/", views.apply_systemd_view, name="apply_systemd"),
    path("<int:server_id>/apply/", views.apply_all_view, name="apply_all"),
    path("<int:server_id>/enable/", views.enable_view, name="enable"),
    path("<int:server_id>/disable/", views.disable_view, name="disable"),
]

multiserver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("multiserver.app.urls", "app"), namespace="app")),
]

multiserver/app/templates/app/list.html
<table class="table table-striped table-sm table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Repo URL</th>
      <th>Port</th>
      <th>Initialized?</th>
      <th>Changes Applied?</th>
      <th>Enabled?</th>
    </tr>
  </thead>
  <tbody>
    {% for server in servers %}
    <tr>
      <td>
        {{ server.name }}
        &nbsp;
        <a href="{% url 'app:detail' server.id %}" class="link-info">
          <i class="bi bi-arrow-up-right-square"></i>
        </a>
      </td>
      <td>{{ server.repo_url }}</td>
      <td>{{ server.port }}</td>
      <td>
        {% if server.initialized %}
        <i class="bi bi-check-circle-fill text-success"></i>
        {% else %}
        <i class="bi bi-x-circle-fill text-danger"></i>
        {% endif %}
      </td>
      <td>
        {% if server.systemd_applied and server.nginx_applied %}
        <i class="bi bi-check-circle-fill text-success"></i>
        {% else %}
        <i class="bi bi-x-circle-fill text-danger"></i>
        {% endif %}
      </td>
      <td>
        {% if server.enabled %}
        <i class="bi bi-check-circle-fill text-success"></i>
        {% else %}
        <i class="bi bi-x-circle-fill text-danger"></i>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

multiserver/app/templates/app/server_detail.html
{% extends "base.html" %}

{% block title %}: Server Detail{% endblock %}

{% block content %}
<div class="d-flex align-items-center">
  <h1>{{ server.name }}</h1>
  &emsp;
  <div class="btn-group">
    <a href="{% url 'app:update' server.id %}" class="btn btn-secondary btn-sm">Edit</a>
    <a href="{% url 'app:delete' server.id %}" class="btn btn-danger btn-sm">Delete</a>
  </div>
</div>
<p>{{ server.description }}</p>

<ul class="list-group">
  <li class="list-group-item"><strong>Service Name:</strong> {{ server.service_name }}</li>
  <li class="list-group-item"><strong>Domain Name:</strong> {{ server.domain_name }}</li>
  <li class="list-group-item"><strong>Repo URL:</strong> {{ server.repo_url }}</li>
  <li class="list-group-item"><strong>Port:</strong> {{ server.port }}</li>
</ul>
<br />

{% if not server.initialized %}
<a href="{% url 'app:initialize' server.id %}" class="btn btn-success">Initialize</a>
{% else %}
{% if not server.systemd_applied %}
<a href="{% url 'app:apply_systemd' server.id %}" class="btn btn-primary">Apply Systemd</a>
{% endif %}
{% if not server.nginx_applied %}
<a href="{% url 'app:apply_nginx' server.id %}" class="btn btn-primary">Apply Nginx</a>
{% endif %}
{% if not server.systemd_applied and not server.nginx_applied %}
<a href="{% url 'app:apply_all' server.id %}" class="btn btn-primary">Apply All</a>
{% endif %}
{% if server.enabled %}
<a href="{% url 'app:disable' server.id %}" class="btn btn-danger">Disable</a>
{% else %}
<a href="{% url 'app:enable' server.id %}" class="btn btn-success">Enable</a>
{% endif %}
{% endif %}

<a href="{% url 'app:list' %}" class="btn btn-primary">
  <i class="bi bi-arrow-left"></i>
  Back to Server List
</a>

<a href="{% url 'admin:app_server_change' server.id %}" class="btn">
  <i class="bi bi-gear"></i>
  Admin
</a>
{% endblock %}

multiserver/app/templates/app/server_list.html
{% extends "base.html" %}

{% block title %}: Manage Servers{% endblock %}

{% block content %}
<h1>Servers</h1>
{% include 'app/list.html' with servers=servers %}


<a href="{% url 'app:create' %}" class="btn btn-primary">
    <i class="bi bi-plus-square"></i>
    &nbsp;
    Create Server
</a>

<a href="{% url 'admin:app_server_changelist' %}" class="btn">
    <i class="bi bi-gear"></i>
    Admin
</a>
{% endblock %}